backend:
  # name: github
  # repo: hothouseinc2/Hothouse-Inc.-Culture
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/assets
public_folder: /assets

publish_mode: editorial_workflow

display_url: https://your-site.com

collections:
  - name: blog
    label: Posts
    folder: src/pages/posts/blog
    create: true
    fields:
      - { name: layout, label: Layout, default: "blog"}
      - { name: type, label: Type, default: "blog"}
      - { name: title, label: Title}
      - { name: tldr, label: TL;DR}
      - { name: date, label: Created At, widget: date }
      - { name: path, label: path, widget: string, default: "/blog" }
      - { name: body, label: Post, widget: markdown}
#   - name: work
#     label: Work
#     folder: src/pages/posts/work
#     create: true
#     fields:
#       - { name: layout, label: Layout, default: "work"}
#       - { name: type, label: Type, default: "work"}
#       - { name: title, label: Title}
#       - { name: tldr, label: TL;DR}
#       - { name: imageNote, label: Image Note, required: false}
#       - { name: svgName, label: SVG File Name, required: false}
#       - { name: description, label: Description}
#       - { name: headerColor, label: Header BG Color, required: false}
#       - { name: metaBackground, label: Meta BG Color, required: false}
#       - { name: linkColor, label: Link Color, required: false}
#       - { name: textColor, label: Text Color, required: false}
#       - { name: textBackground, label: Post BG Color, required: false}
#       - { name: website, label: Website, required: false}
#       - { name: date, label: Created At, widget: date }
#       - { name: path, label: path, widget: string, default: "/work" }
#       - { name: body, label: Post, widget: markdown}

# editor:
#   preview: false